
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABSTRACT ADD AND ARRAY_CREATION ARRAY_DECLARATION AS ASIGNAR BASE BOOL BOOL_LITERAL BREAK BYTE CASE CATCH CHAR CHAR_LITERAL CHECKED CLASS COMA CONSOLE CONSOLE CONST CONTINUE DCORCH DECIMAL DECREMENTO DEFAULT DELEGATE DICTIONARY DIFERENTE DIVIDIR DIVIDIRIGUAL DLLAVE DO DOUBLE DPAREN DYNAMIC ELSE ENUM EVENT EXTERN FALSE FINALLY FIXED FLECHALAMBDA FLOAT FLOAT_LITERAL FOR FOREACH GENERICO_INVALIDO GET GOTO ICORCH IDENTIFICADOR ID_INVALIDO IF IGUAL ILLAVE IN INCREMENTO INT INTERFACE INTERNAL INT_LITERAL IPAREN IS LISTA LOCK LONG MAS MASIGUAL MAYOR MAYORIGUAL MENOR MENORIGUAL MENOS MENOSIGUAL MODULO NAMESPACE NEW NOT NULL OBJECT OPERATOR OR OUT OVERRIDE PARAMS PARTIAL POR PORIGUAL PRIVATE PROTECTED PUBLIC PUNTO READONLY REF REMOVE RETURN SBYTE SEALED SENTENCIAFIN SET SHORT SIZEOF STACKALLOC STATIC STRING STRING_LITERAL STRUCT SWITCH THIS THROW TRUE TRY TYPEOF UINT ULONG UNCHECKED UNSAFE USHORT USING VAR VIRTUAL VOID VOLATILE WHILE WRITELINE WRITELINE YIELD\n    impresion : CONSOLE PUNTO WRITELINE IPAREN imprimibles DPAREN SENTENCIAFIN\n    \n        imprimibles : IDENTIFICADOR\n        | BOOL_LITERAL\n        | CHAR_LITERAL\n        | STRING_LITERAL\n        | FLOAT_LITERAL\n        | INT_LITERAL\n    \n    linea : impresion \n    \n    cuerpo : linea\n    | linea cuerpo\n    '
    
_lr_action_items = {'CONSOLE':([0,],[2,]),'$end':([1,14,],[0,-1,]),'PUNTO':([2,],[3,]),'WRITELINE':([3,],[4,]),'IPAREN':([4,],[5,]),'IDENTIFICADOR':([5,],[7,]),'BOOL_LITERAL':([5,],[8,]),'CHAR_LITERAL':([5,],[9,]),'STRING_LITERAL':([5,],[10,]),'FLOAT_LITERAL':([5,],[11,]),'INT_LITERAL':([5,],[12,]),'DPAREN':([6,7,8,9,10,11,12,],[13,-2,-3,-4,-5,-6,-7,]),'SENTENCIAFIN':([13,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'impresion':([0,],[1,]),'imprimibles':([5,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> impresion","S'",1,None,None,None),
  ('impresion -> CONSOLE PUNTO WRITELINE IPAREN imprimibles DPAREN SENTENCIAFIN','impresion',7,'p_impresion','sintactico.py',8),
  ('imprimibles -> IDENTIFICADOR','imprimibles',1,'p_imprimibles','sintactico.py',12),
  ('imprimibles -> BOOL_LITERAL','imprimibles',1,'p_imprimibles','sintactico.py',13),
  ('imprimibles -> CHAR_LITERAL','imprimibles',1,'p_imprimibles','sintactico.py',14),
  ('imprimibles -> STRING_LITERAL','imprimibles',1,'p_imprimibles','sintactico.py',15),
  ('imprimibles -> FLOAT_LITERAL','imprimibles',1,'p_imprimibles','sintactico.py',16),
  ('imprimibles -> INT_LITERAL','imprimibles',1,'p_imprimibles','sintactico.py',17),
  ('linea -> impresion','linea',1,'p_linea','sintactico.py',22),
  ('cuerpo -> linea','cuerpo',1,'p_cuerpo','sintactico.py',27),
  ('cuerpo -> linea cuerpo','cuerpo',2,'p_cuerpo','sintactico.py',28),
]
